"""
    errors.jl

Probabilistic error models combining measurement noise and model bias.
"""

using Distributions
using LinearAlgebra

# ============================================================================
# Model wrapper type
# ============================================================================

"""
    ModelClass(f)

A thin callable wrapper around a function. Instances can be called like a
function with keyword arguments, which are forwarded to the wrapped function.
Only keyword arguments that the wrapped function accepts are passed through.

Examples
    julia> model_function(;x, y=1) = x + y
    julia> model = ModelClass(model_function)
    julia> model(;x=2, y=3, z=999)  # z is ignored
    5
"""
struct ModelClass{F}
    f::F
    valid_kwargs::Set{Symbol}
    has_kwargs_splat::Bool
    
    function ModelClass(f::F) where F
        # Collect all valid kwarg names from all methods
        valid_kwargs = Set{Symbol}()
        has_kwargs_splat = false
        
        for method in methods(f)
            kwarg_names = Base.kwarg_decl(method)
            union!(valid_kwargs, kwarg_names)
            if :kwargs ∈ kwarg_names
                has_kwargs_splat = true
            end
        end
        
        new{F}(f, valid_kwargs, has_kwargs_splat)
    end
end

function (m::ModelClass)(; kwargs...)
    # If the function has kwargs..., pass everything through
    if m.has_kwargs_splat
        return m.f(; kwargs...)
    end
    
    # Filter kwargs to only include valid ones
    filtered_kwargs = filter(kv -> kv.first ∈ m.valid_kwargs, kwargs)
    return m.f(; filtered_kwargs...)
end

# ============================================================================
# Covariance Specification Types
# ============================================================================

"""
    CovarianceSpec

Abstract type for covariance specifications.
Can be either a constant matrix or a function that generates a covariance matrix.
"""
abstract type CovarianceSpec end

"""
    ConstantCovariance <: CovarianceSpec

A constant covariance matrix.

# Fields
- `Σ::AbstractMatrix`: The covariance matrix
"""
struct ConstantCovariance <: CovarianceSpec
    Σ::AbstractMatrix
    
    function ConstantCovariance(Σ::AbstractMatrix)
        # Validate that Σ is symmetric and positive semi-definite
        if !issymmetric(Σ)
            throw(ArgumentError("Covariance matrix must be symmetric"))
        end
        new(Σ)
    end
end

# Constructor from vector (diagonal covariance)
ConstantCovariance(σ::AbstractVector) = ConstantCovariance(Diagonal(σ .^ 2))

"""
    FunctionalCovariance <: CovarianceSpec

A covariance matrix generated by a function.

# Fields
- `f::Function`: Function that takes inputs and returns a covariance matrix

The function signature should be: `f(args...) -> AbstractMatrix`
"""
struct FunctionalCovariance <: CovarianceSpec
    f::Function
end

"""
    ZeroCovariance <: CovarianceSpec

A zero covariance matrix (all entries zero).
"""
struct ZeroCovariance <: CovarianceSpec end

# ============================================================================
# Helper functions to evaluate covariance
# ============================================================================

"""
    evaluate_covariance(cov::ConstantCovariance, args...)

Evaluate a constant covariance (ignores args).
"""
function evaluate_covariance(cov::ConstantCovariance; args...)
    Σ = cov.Σ
    
    # Validate symmetry
    if !issymmetric(Σ)
        throw(ArgumentError("Covariance matrix is not symmetric"))
    end
    
    return Σ
end

"""
    evaluate_covariance(cov::FunctionalCovariance; args...)

Evaluate a functional covariance by calling the function.
Validates symmetry.
"""
function evaluate_covariance(cov::FunctionalCovariance; args...)
    Σ = cov.f(;args...)
    
    # Validate symmetry
    if !issymmetric(Σ)
        throw(ArgumentError("Functional covariance returned non-symmetric matrix"))
    end
    
    return Σ
end

# ============================================================================
# ProbabilisticError Distribution
# ============================================================================

"""
    ProbabilisticError <: Distribution{Multivariate, Continuous}

A multivariate normal distribution representing combined measurement noise and model bias.

The total error is: ε ~ Normal(0, Σ_y + Σ_d)

where:
- Σ_y: measurement noise covariance
- Σ_d: model bias/discrepancy covariance

# Fields
- `Σ_y::CovarianceSpec`: Measurement noise covariance specification
- `Σ_d::CovarianceSpec`: Model bias covariance specification

# Constructors
```julia
ProbabilisticError(Σ_y, Σ_d)
```

# Examples
```julia
using BayesJL, LinearAlgebra

# Constant covariances
Σ_y = ConstantCovariance(Diagonal([1.0, 1.0, 1.0]))
Σ_d = ConstantCovariance(Diagonal([0.5, 0.5, 0.5]))
err = ProbabilisticError(Σ_y, Σ_d)
```
"""
struct ProbabilisticError{Sy<:CovarianceSpec, Sd<:CovarianceSpec} <: Distribution{Multivariate, Continuous}
    Σ_y::Sy
    Σ_d::Sd
    
    function ProbabilisticError(Σ_y::CovarianceSpec, Σ_d::CovarianceSpec=ZeroCovariance())
        new{typeof(Σ_y), typeof(Σ_d)}(Σ_y, Σ_d)
    end
end

# ============================================================================
# Distribution Interface
# ============================================================================

import Distributions: logpdf, pdf, length
import Random

# Base.length(d::ProbabilisticError) = size(d.Σ_y, 1)

"""
    logpdf(d::ProbabilisticError, e::AbstractVector, args...)

Compute log probability density of observing `e` under the error model.

Additional `args` are passed to functional covariances if present.
"""
function logpdf(d::ProbabilisticError, e::AbstractVector; args...)
    # Evaluate both covariances
    Σ_y = evaluate_covariance(d.Σ_y; args...)
    Σ_d = isa(d.Σ_d, ZeroCovariance) ? zeros(size(Σ_y)) : evaluate_covariance(d.Σ_d; args...)

    @assert size(Σ_y, 1) == length(e) "Dimension mismatch between Σ_y and error vector"
    @assert size(Σ_d, 1) == length(e) "Dimension mismatch between Σ_d and error vector"

    # Compute total covariance
    Σ_total = Σ_y + Σ_d
    
    # Validate positive definiteness of total covariance
    d = det(Σ_total)
    if d <= 0
        throw(ArgumentError("Total covariance matrix is not positive definite (det = $d)"))
    end
    
    # Create MvNormal and evaluate
    dist = MvNormal(zeros(length(e)), Σ_total)
    return logpdf(dist, e)
end

"""
    pdf(d::ProbabilisticError, e::AbstractVector; args...)

Compute probability density of observing `e` under the error model.
"""
pdf(d::ProbabilisticError, e::AbstractVector, args...) = exp(logpdf(d, e, args...))

"""
    rand([rng], d::ProbabilisticError; args...)
    rand([rng], d::ProbabilisticError, n::Int; args...)

Sample from the error distribution.

Additional `args` are passed to functional covariances if present.
"""
function Random.rand(rng::Random.AbstractRNG, d::ProbabilisticError; args...)
    Σ_y = evaluate_covariance(d.Σ_y; args...)
    Σ_d = isa(d.Σ_d, ZeroCovariance) ? zeros(size(Σ_y)) : evaluate_covariance(d.Σ_d; args...)

    Σ_total = Σ_y + Σ_d
    
    dist = MvNormal(zeros(size(Σ_total, 1)), Symmetric(Σ_total))
    return rand(rng, dist)
end

function Random.rand(rng::Random.AbstractRNG, d::ProbabilisticError, n::Int; args...)
    Σ_y = evaluate_covariance(d.Σ_y; args...)
    Σ_d = isa(d.Σ_d, ZeroCovariance) ? zeros(size(Σ_y)) : evaluate_covariance(d.Σ_d; args...)
    
    Σ_total = Σ_y + Σ_d
    
    dist = MvNormal(zeros(size(Σ_total, 1)), Symmetric(Σ_total))
    return rand(rng, dist, n)
end

# Versions without explicit RNG
Base.rand(d::ProbabilisticError; args...) = rand(Random.default_rng(), d; args...)
Base.rand(d::ProbabilisticError, n::Int; args...) = rand(Random.default_rng(), d, n; args...)